### PR TITLE
runs iwyu on the code base

### LINKED ISSUE #583: <gsl/string_span> uses std::add_const without including <type_traits>
Obviously the implementation is picking up <type_traits> indirectly from another thing that is included, but we should be explicit about including what we use in a header.

### PR DESCRIPTION
**Pull request by tiagomacarios**
I ran it with the --comment flag to get clangs reasoning for the include.

Should fix #583 and supersedes #584.

@paweldac @LegalizeAdulthood wdyt?

### CODE REVIEW

**Comment by tiagomacarios** [comment]
I can try to add a travis config for the build to check for this problems

**Comment by paweldac** [comment]
Hi @tiagomacarios

It looks fine to me.

**Comment by LegalizeAdulthood** [comment]
Looks good to me!

**Comment by tiagomacarios** [comment]
@neilmacintosh bump!

**Comment by neilmacintosh** [comment]
Looks good to me @tiagomacarios, thanks!

**Pull request merged**
