### PR TITLE
Fix gcc build

### PR DESCRIPTION
**Pull request by AntonBikineev**
This fixes build with gcc (at least 7.2.0)

### CODE REVIEW

**Comment by menete** [comment]
Refering to #525 , #526 Is there any consensus on how to proceed with this issue ?

**Comment by gdr-at-ms** [comment]
The template parameters should be kept as `ptrdiff_t`; the problem is the compiler; aren't there GCC-specific ways of telling it to stop complaining here?

**Comment by menete** [comment]
Sure if the goal is just to silence the compiler there is
```
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wsign-conversion"
```
as well as
```
#pragma GCC diagnostic pop
```
If those are applied on top/bottom of the files `span` and `multi_span` gcc compiles the tests withou a warning.
Of course the pragmas can also be applied a bit more selectively.

**Comment by menete** [comment]
@gdr-at-ms #690 implements a solution based on the pragmas above, is this the kind of approach you where proposing?

**Comment by gdr-at-ms** [comment]
@menete Yes, that looks good to me.

**Comment by annagrin** [comment]
fixed in #690 . Thanks all!

**Pull request closed without merging**
