### PR TITLE
CI updates:

### PR DESCRIPTION
**Pull request by CaseyCarter**
Travis: use cmake 3.7
Appveyor: Add .appveyor.yml config, test VS2013/VS2015/VS2017 x86/x64 Debug/Release.

I think @neilmacintosh may need to fix his AppVeyor configuration and tell it to simply use appveyor.yml.

### CODE REVIEW

**Comment by CaseyCarter** [comment]
> I think @neilmacintosh may need to fix his AppVeyor configuration and tell it to simply use appveyor.yml.

Nope - looks like AppVeyor picked the yml right up.

**Comment by neilmacintosh** [comment]
Thanks Casey, this looks good. But can I ask you to make one small change?

Can you drop VS 2013 from the AppVeyor config? I think you asked somewhere else about whether 2013 is still supported.

World: As per my announcement at CppCon and reply to an issue on here...VS 2013 is unsupported now that VS 2017 has been released. So dropping CI support will enact "phase 1" of discountinuing support. That will then allow us to go do the nice source cleanup as "phase 2".

**Comment by CaseyCarter** [comment]
> Can you drop VS 2013 from the AppVeyor config?

Done. (and there was much rejoicing.)

**Comment by neilmacintosh** [comment]
Thanks @CaseyCarter you have helped move us into the future ;-)

**Pull request merged**
