### PR TITLE
explicit not_null constructor

### PR DESCRIPTION
**Pull request by akrzemi1**
See also https://github.com/Microsoft/GSL/issues/395

### CODE REVIEW

**Comment by MikeGitb** [comment]
I think you need to update the respective unit tests too. I don't know, if that would trigger a cla requriement though.

**Comment by akrzemi1** [comment]
Please, can you push my fix and apply the unit test updates yourself? If I try to add unit-tests, the whole process of license agreement starts. I do not want Microsoft to collect my personal data.

**Comment by neilmacintosh** [comment]
@akrzemi1 I can't knowingly take a pull request that breaks the CI builds. I believe it is basic engineering etiquette to fix the breaks that result from your change before expecting it to be accepted.

I'm sorry to hear that you don't want to sign the Contributor License Agreement. The purpose of that agreement is to make sure that this open source project works effectively for everyone. The reason we collect your personal data (name, email and address) is to help guard all of us who use and contribute to the GSL (whether we work at Microsoft or not) against claims of patent or copyright infringement.

I understand people are nervous about collection of their personal data. In the same way, I am nervous about accepting contributions unless I can be sure they are free of claims that would undermine our efforts to provide open source software to the wider C++ community.

Unless you are prepared to sign the agreement and fix the tests, then I cannot accept the PR. Given there was a past PR that attempted to fix the issue, I may go back and revive that when I next get a chance.

**Comment by akrzemi1** [comment]
In any case, we would probably want to continue with this pull request: https://github.com/Microsoft/GSL/pull/401

Sorry, I do not know exactly how GitHub pull requests work, so I ended up creating another one with unit tests.

**Comment by akrzemi1** [comment]
@neilmacintosh Thank you for the explanation. I understand your position.

**Comment by neilmacintosh** [comment]
Thanks @akrzemi1. I'll close this PR out for now.

**Pull request closed without merging**
