### PR TITLE
Add a table of features

### PR DESCRIPTION
**Pull request by kuzkry**
Hello!
I believe it would compose nicely with https://github.com/isocpp/CppCoreGuidelines/pull/1516.
And please help me with `strided_span` cause I have no idea what that beast might be.

### CODE REVIEW

**Comment by JordanMaples** [comment]
Maintainers' call: Looks great, I just need to verify all of the information before I merge it. Thanks for your contribution.

**Comment by kuzkry** [comment]
Cool, thanks! Please don't forget about `strided_span`.

**Comment by JordanMaples** [comment]
Well that's not what I expected it to do. Let me look at how I can clean this up.

**Comment by JordanMaples** [comment]
Looks like it's cleaned up.

**Comment by kuzkry** [comment]
Hey @JordanMaples! I managed to forget about this PR :)
Thanks for the clean-up and especially for the update of some entries.
Btw. I see you've been playing a bit with merge commit and it's a bit cluttered (2 of 7 commits introduce actual changes) so I'll prepare a nice rebase from where we can carry on our discussion.

**Comment by kuzkry** [comment]
Ok, rebase is done. I introduced no changes compared to the tip of your previous work (3beef9e).

**Comment by JordanMaples** [comment]
Thanks for the rebase and for all of your patience.

**Pull request merged**
