### PR TITLE
Initial support for CTAD for spans.

### PR DESCRIPTION
**Pull request by LYP951018**
Related issue #680 .

### CODE REVIEW

**Comment by LYP951018** [comment]
It seems that I forgot to wrap deduction guides with cplusplus. I'll fix that soon.

**Comment by LYP951018** [comment]
I think we need some macro to indicate whether deduction guide is available.

**Comment by annagrin** [comment]
Thanks @LYP951018.  How about this one: __cpp_deduction_guides? 

I found it in https://en.cppreference.com/w/cpp/feature_test, but haven't tried myself yet.

**Comment by jwakely** [comment]
`#if __cpp_deduction_guides >= 201606` is the right check.

**Comment by LYP951018** [comment]
My concerns here is that there will be many places require something like:

```cpp
#if __cpp_deduction_guides >= 201606
```

And I should introduce some macro:

```cpp
#if __cpp_deduction_guides >= 201606
#define GSL_HAS_DEDUCTION_GUIDES
#endif 
```

Where should I put the macro definition in?

**Comment by MikeGitb** [comment]
How is checking for that macro better than directly checking for the standard feature macro?

Btw.: Why do we have to check for a particular version instead of just checking for the presence?

**Comment by jwakely** [comment]
You don't *have* to, but the value tells you if the version you care about is supported. For some features different values mean different things are supported.

**Comment by hsutter** [comment]
Guidelines editors call: Yes please add CTAD. Thanks!

**Comment by JordanMaples** [comment]
Closing this PR. Deduction guides were was added as a part of #844.

**Pull request closed without merging**
