### PR TITLE
not_null constructor is now explicit

### PR DESCRIPTION
**Pull request by ericLemanissier**
solves #395

### CODE REVIEW

**Comment by beinhaerter** [comment]
Just curious: what's the reason to change the initialization in the tests and why have different initialization ("{}" vs. "()") in the same test?

**Comment by ericLemanissier** [comment]
it was just a way to check they all work. I can harmonize them if it is a blocking point

**Comment by beinhaerter** [comment]
OK, thanks, that was my guess.

**Comment by xaxxon** [comment]
I question the usefulness and desirability of this change.

**Comment by xaxxon** [comment]
an alternative would be to make a new type explicit_not_null or something if this behavior is desired.

**Comment by Amaroker** [comment]
> I question the usefulness and desirability of this change as stated in the associated issue - especially as a breaking change.

Changing a parameter to not_null can be a breaking change, regardless if the constructor is explicit or not.

However, the explicit constructor is very useful because we don't want such changes to silently (until run-time) break something.

The sooner we have the explicit constructor, the better.

The core guidelines say:

- Prefer compile-time checking to run-time checking.

- Single-argument constructors should be declared explicit. 

- Do not introduce implicit conversions (through conversion operators or non-explicit constructors) just to gain a minor convenience.

**Comment by xaxxon** [comment]
This breaks code which already uses notnull.

**Comment by ericLemanissier** [comment]
@neilmacintosh What do you think about this pull request ?

**Comment by neilmacintosh** [comment]
@ericLemanissier I personally like this change, for the reasons observed on the issue threads: `not_null` will frequently be used to make a function have a strong contract about null values, and it seems sensible to ask callers to explicitly acknowledge that contract.

I'll leave final approval to @annagrin though.

**Comment by annagrin** [comment]
@neilmacintosh Agreed. We do want to follow the Guidelines in GSL:)

**Pull request merged**
