### PR TITLE
writting <> with every string_view type is non productive and also di…

### PR DESCRIPTION
**Pull request by kevgs**
…ffers from what C++ Core Guidelines proposes

### CODE REVIEW

**Comment by kevgs** [comment]
Looks like clang++-3.6 isn't working on travis server for some reason.

**Comment by tamaskenez** [comment]
@kevgs https://github.com/travis-ci/apt-source-whitelist/issues/156

**Comment by neilmacintosh** [comment]
For now, the <> implements the design correctly and is just a requirement of the language. It may be annoying but it does allow us to write string_view<10> (for example) when we want to specify a fixed-size string_view,

**Comment by tamaskenez** [comment]
What about separate string_view and string_view_n? I think dynamic-range views are far more common.

    template<size_t Extent>
    using string_view_n = basic_string_view<char, Extent>;

and

    using string_view = basic_string_view<char>;

**Comment by neilmacintosh** [comment]
Sure, they are. We've certainly considered that option (with a couple of different name variants). I'll see what people think on the committee as we propose this type for standardization and if we end up with that type of naming scheme, then it will be reflected here.

**Pull request closed without merging**
