### PR TITLE
add travis testing (gcc5, clang36)

### PR DESCRIPTION
**Pull request by tamaskenez**
Implements #27

To activate testing:
- before accepting this PR please enable this repo at https://travis-ci.org/
- merging the PR will trigger a travis run

### CODE REVIEW

**Comment by kylog** [comment]
Yes, please enable travis CI. It's free and a good minimum bar for pull requests.

After that, enabling appveyor CI would also be great :)

**Comment by neilmacintosh** [comment]
I will take a look at this shortly.

**Comment by gdr-at-ms** [comment]
Applied.

**Comment by kylog** [comment]
Although the clang builds failed: https://travis-ci.org/Microsoft/GSL/jobs/82048533

**Comment by tamaskenez** [comment]
I'm checking it...

**Comment by tamaskenez** [comment]
On my fork it has been solved by itself. I guess someone over at travis or llvm.org has fixed it.
Next commit here will trigger a new travis run, I hope it'll be fine then.

**Pull request merged**
