### PR TITLE
Move from unittest-cpp to catch for unit testing.

### LINKED ISSUE #495: Update to Catch instead of UnitTest-cpp
I have an updated Travis CI script that adds Clang Format, Clang 3.9, Clang 4.0, and Git Check. Apparently, Clang 3.9 and Clang 4.0 have been broken for some time now as UnitTest-cpp segfaults with these compilers on it's own unit tests. 

To add to the issues with UnitTest-cpp, on my own project, UnitTest-cpp cannot compile at all on Cygwin, which means neither can the GSL which prevents automated testing with the GSL on AppVeyor Cygwin builds. We currently patch the GSL to remove UnitTest-cpp so that the GSL works in all environments (GCC, Clang, Cygwin and Windows). 

The simple solution is to move to Catch.hpp which is a simple, header only library that works in all of these environments. Furthermore, the syntax is very similar to UnitTest-cpp, so the diff will not be that large. Catch.hpp is also a much larger project with regular updates, while UnitTest-cpp hasn't been updated in 3 months. 

My Proposal:
- PR#1: Move to Catch.cpp, update unit tests
- PR#2: Update Travis CI script 

I already have PR#2 done, but I don't want to start PR#1 without a blessing from @neilmacintosh

### PR DESCRIPTION
**Pull request by neilmacintosh**
Many thanks to @rianquinn. This should fix #495, #494 and #529.

### CODE REVIEW

**Comment by rianquinn** [comment]
Awesome. Once this is merged I will start work on getting the clang-format stuff integrated into Travis CI as we discussed.

**Comment by rianquinn** [comment]
oh, and will also up-rev the version of catch to include the NO_SELFTEST work that we go upstreamed which should speed up Travis.

**Comment by neilmacintosh** [comment]
Actually...you can't just up-rev the version of catch at will I'm afraid. Each time we change the version that we snap to, I need to update legal documentation to keep everyone happy.

Are there likely to be other upgrades/changes to Catch worth waiting on so we can batch up that effort?

**Comment by rianquinn** [comment]
I'm not sure, but we are in no hurry either. As far as I know, the answer is no as we are not really using that much of Catch.hpp. Most of the cygwin issues that I know of have been fixed in the version you have, and it works fine with VS, GCC and Clang.

**Comment by neilmacintosh** [comment]
Great. So this seems like the right version to start from. Let's sit with it for a little while (a month or so) and if nothing else worth waiting for appears to be on the horizon, we can bump the version.

**Comment by rianquinn** [comment]
sounds great

**Pull request merged**
