### PR TITLE
PR to address issue #101

### PR DESCRIPTION
**Pull request by RicoAntonioFelix**
On an attempt to strip down the gsl.h, in this PR I have first removed the final_act class from it into its own file and renamed it to correspond to the guidelines...

### CODE REVIEW

**Comment by neilmacintosh** [comment]
I appreciate the name change for final_action and breaking it into its own file. However, I would prefer it if we could leave the original member names and have fewer empty-comment lines as per the original. Minimizing non-functional changes makes it easier to review a PR :-)

Also, I suspect this file will need compiler-workaround macros (see those in gsl.h, for example) to stop the noexcept from breaking MSVC 2013.

**Comment by neilmacintosh** [comment]
@RicoAntonioFelix did you want to try and address my comments and the conflicts this PR now has, or shall I close this out?

**Comment by RicoAntonioFelix** [comment]
I think its best to close this out since @trebconnell is very active and doing a good job taking care of things... We should just let the types and library mature before doing a major restructuring of the module...

**Comment by neilmacintosh** [comment]
Thanks for getting back to me on that @RicoAntonioFelix. I'll close this out for now.

**Pull request closed without merging**
