### PR TITLE
Make narrow constexpr

### PR DESCRIPTION
**Pull request by johelegp**
I hope Visual Studio 2015 works.

### CODE REVIEW

**Comment by johelegp** [comment]
Doesn't work for Visual Studio 2015 nor GCC 5. When you drop Visual Studio 2015 support, consider also dropping support for GCC 5. I'll reopen when those two compilers are no longer supported.

**Comment by annagrin** [comment]
@johelegp  If you want to ifdef around its ok - it will go away when the support for an old version goes away.

**Comment by johelegp** [comment]
Thanks for the suggestion, I'll give it a go.

I just noticed the `#define constexpr /*constexpr*/` when `_MSC_VER < 1910`. If I guard the test with that, then Visual Studio 2015 tests should pass. However, GCC 5 will continue to fail. But this is the first `constexpr` test, so perhaps I shouldn't test and call it a day?

**Comment by annagrin** [comment]
@johelegp I guess the test should be guarded with the same logic as defining constexpr away.

**Comment by johelegp** [comment]
Thanks. I've done that, with the addition of detecting GCC 5 to not test when the macro `GSL_DONT_TEST_CONSTEXPR` is defined.

**Comment by johelegp** [comment]
If this PR is desired, I could merge the definition for `GSL_DONT_TEST_CONSTEXPR` as
`#if defined(_MSC_VER) && _MSC_VER < 1910` for each block, or have one block like
`#if (defined(_MSC_VER) && _MSC_VER < 1910) || (!defined(__clang__) && defined(__GNUC__) && __GUNC__ < 6)`.

**Comment by annagrin** [comment]
@johelegp should we ifdef in the library itself, not in tests, so older compilers could you narrow as well?

**Comment by johelegp** [comment]
Right. Thanks for your support. Does the macro use looks right?

**Comment by annagrin** [comment]
thanks @johelegp !

**Pull request merged**
