### PR TITLE
Remove #pragma once

### PR DESCRIPTION
**Pull request by bjude**
Core Guidelines SF.8 recommends using portable include guards instead.
Addresses issue  #545 

NOTE: I haven't completed the CLA yet, the site seems to be down. I'm opening the pull request now because i had some free time. Merging may have to wait till i've completed that.

### CODE REVIEW

**Comment by predator5047** [comment]
Pragma once is supported by all the major compiler  (clang since 2013, IBM since 2015, gcc since 2013, intel since 2013). And since GSL requires C++14 it's very likely that the compiler supports it.

**Comment by tiagomacarios** [comment]
@predator5047 You are correct. The issue is that it is "against" the guidelines: http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#sf8-use-include-guards-for-all-h-files

**Comment by MikeGitb** [comment]
There is simply no advantage in having both, include guards and `#pragma once` and using only `#pragma once` is highly controversial.

**Comment by neilmacintosh** [comment]
Thanks for putting this pack together @bjude, it looks great. I'm just waiting on the CLA so I can squash-n-merge. I'm sorry to hear the site was down earlier. Let me know if it continues to cause you any problems.

**Comment by tiagomacarios** [comment]
@bjude @neilmacintosh 
I have this change sitting for a while: https://github.com/tiagomacarios/GSL/tree/drop_pragma
was waiting for #566 to get merged.

**Comment by bjude** [comment]
Signed the CLA yesterday, should be good to go.

**Comment by bjude** [comment]
Rebased and removed the pragma from the new pointers header.
This and PR #571 are now effectively the same, just using different include guards.

I'll leave it to @neilmacintosh to decide which one fits the bill.

**Comment by neilmacintosh** [comment]
Thanks @bjude, this looks good to me. I'm going to take this PR in first as it is small and simple. I can always take the PR from @tiagomacarios as well to pick up the guard-name changes.

**Pull request merged**
