### PR TITLE
Protect against overloaded operator&

### LINKED ISSUE #661: `span`'s constructors should use `addressof`
I was trying to construct a `span<ComPtr<T>>` from `array<ComPtr<T>, N>` and then I got tons of compilation errors ... Then I found `ComPtr` overloads `operator&` which returns `Details::ComPtrRef<ComPtr<T>>` and `span`'s constructors for arrays rely on `&arr[0]`, which leads to the error.

Maybe I could submit a pr for this? :)

### PR DESCRIPTION
**Pull request by LYP951018**
Fix #661 .

### CODE REVIEW

**Comment by neilmacintosh** [comment]
@LYP951018, I was wondering if you could add some unit tests that demonstrate an overloaded `operator&` that causes a problem with the old implementation and then fails to disrupt the implementation with your changes.

**Comment by xaxxon** [comment]
I'm curious of a *valid* use for overloading operator& and how this should behave in that situation.

**Comment by LYP951018** [comment]
@neilmacintosh Unit tests have been added.

**Comment by annagrin** [comment]
Thanks @LYP951018, your change is included #723, appreciate your help!

**Pull request closed without merging**
