### PR TITLE
Fix gcc build problem

### PR DESCRIPTION
**Pull request by beinhaerter**
Closes issue #1148 by fixing problems introduced in PR #1140.

### CODE REVIEW

**Comment by beinhaerter** [comment]
This pull request is waiting to be merged since two monthes. Is there something missing or needs to be done?

**Review by gdr-at-ms — APPROVED** [review]

**Comment by d-winsor** [comment]
@beinhaerter There appears to be problems with the checks running on older PRs. Can you please push an empty commit to retrigger tests.

**Comment by beinhaerter** [comment]
> @beinhaerter There appears to be problems with the checks running on older PRs. Can you please push an empty commit to retrigger tests.

I did an amend and a force push, but that did not seem to help.

**Comment by beinhaerter** [comment]
This PR is today open since 5 months. When will it finally be merged?

Is Microsoft still working on this repo? Is it still a good library to use in our projects? Or is it dead and we better look for a replacement?

**Comment by beinhaerter** [comment]
This PR is today open since half a year. When will it finally be merged?

Is Microsoft still working on this repo? Is it still a good library to use in our projects? Or is it dead and we better look for a replacement?

**Comment by grahamreeds** [comment]
There are flurries of activity occasionally. Remember most of the people
are busy getting the next version of C++ to the station on time!

I agree that if a compatibility issue has cropped up and the pull request
fixes it then it should be merged.

As for whether you should be using it or something else my question is that
if it does what you want it to do does it need to be actively worked on?

**Comment by beinhaerter** [comment]
> I agree that if a compatibility issue has cropped up and the pull request fixes it then it should be merged.
> As for whether you should be using it or something else my question is that if it does what you want it to do does it need to be actively worked on?

I don't expect that new features are added. I know GSL implements what the Core Guidelines require. So there is no need for active development aside any bug fixes.
As you said, I do expect that fixes get merged in a timely manner. This helps all users of the GSL.

Speaking as a contributor I can say that I try to help make GSL better, here I try to help others that ran into the clang build problem. The fix is short, so not much time is required to review and merge (except the CI problem), but yet the PR is still not merged and there is no information if and when it will be merged. That is frustrating and reduces my motivation to contribute to the project.

> Remember most of the people are busy getting the next version of C++ to the station on time!

That is good to know.

**Comment by carsonRadtke** [comment]
@beinhaerter Thank you for the contribution!

We understand your frustration and apologize that this PR been open since March. We will be more diligent in responding to bugs and PRs going forward.

**Pull request merged**
