### PR TITLE
We should be using standard algorithms where possible.

### PR DESCRIPTION
**Pull request by kernhanda**
Use of algorithms in the STL should be promoted where possible.
Also fixed up some whitespace issues.

### CODE REVIEW

**Comment by neilmacintosh** [comment]
In principle, I like the idea of using STL algorithms where appropriate. However, the PR appears to fail the travis-ci checks. Additionally, it changes the line endings in use in the existing files. Both of these issues would need to be corrected.

**Comment by kernhanda** [comment]
Fixed the whitespace changes and fixed the build break.

**Comment by neilmacintosh** [comment]
Thanks...unfortunately it appears to have conflicts again now. Once you have them resolved I will take another look.

**Comment by kernhanda** [comment]
Fixed conflicts.

**Comment by neilmacintosh** [comment]
Looks like you have failing tests now.

**Comment by neilmacintosh** [comment]
My mistake...the test failure was not yours! It's green again. However, I'm still seeing line ending changes that look to be purely whitespace diffs....can you address that?

**Comment by kernhanda** [comment]
I don't see any whitespace changes in the latest diff. Even checking it out through the command line results in no indication of whitespace changes. I'm taking a look at https://github.com/Microsoft/GSL/pull/57/files.

**Comment by neilmacintosh** [comment]
Agreed, the diff lost the whitespace changes now. So it all looks good to me. Thanks for the change @kernhanda!

**Pull request merged**
