### PR TITLE
Add Visual Studio 2019 image for tests

### PR DESCRIPTION
**Pull request by NN---**
Refer to https://github.com/appveyor/ci/issues/2907
VS2019 is enabled per request.

### CODE REVIEW

**Comment by annagrin** [comment]
Thanks @NN, I appreciate the VS2019 support! It seems to me that appveyor’s VS 2019 image is missing clang and llvm tools. I send them an email to figure out what needs to be done on this case. For now, you can try disabling the clang-cl scenario for VS2019 in the text matrix, or wait until we hear the news. Will keep this thread updated.

**Comment by NN---** [comment]
Clang is on the way https://github.com/appveyor/ci/issues/2964
Other tools will be added soon.

**Comment by NN---** [comment]
@annagrin As you can see AppVeyor added clang and there is a successful build.

**Comment by annagrin** [comment]
Thanks @NN--- !

**Pull request merged**
