### PR TITLE
Adding not_null comparison operators for raw pointers

### PR DESCRIPTION
**Pull request by kernhanda**
Fixes issue #521

### CODE REVIEW

**Comment by Amaroker** [comment]
I'm still curious as to why Visual C++ has this limitation. GCC and Clang works without this fix.

**Comment by kernhanda** [comment]
Ping.

**Comment by xaxxon** [comment]
This is a lot of complexity and code to add for a workaround for what is likely a compiler bug.   I'd suggest further looking into alternative solutions if this compiler is required to be supported.

**Comment by annagrin** [comment]
@kernhanda thank you for reporting the compiler issue! I opened a bug for msvc, so this will get sorted out. If you need those to work for compiler versions with the bug, I suggest to add those operators on your side for now. Closing the issue.

**Comment by Amaroker** [comment]
@annagrin  Hi, it was I who reported this issue here. I also reported it to Developer Community (id 389748, active with status "Under Investigation" for some time now).

**Pull request closed without merging**
