### PR TITLE
not_null and maybe_null variants should only work on pointer types.

### PR DESCRIPTION
**Pull request by kernhanda**

### CODE REVIEW

**Comment by trebconnell** [comment]
[GSL.View](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#gslview-views) specifies that not_null can be a non-pointer type.  My PR #51 fixes some issues around this.

**Comment by kernhanda** [comment]
There are a number of these issues that are cropping up, all of which beg the questions: how on sync do we want the two and which one usually has higher precedence?

**Comment by trebconnell** [comment]
I've largely moved over to raising issues on isocpp since this is theoretically just an implementation of that (though it's very vague about a lot of things).  I feel this implementation is sitting on a foundation that may be shifting a lot, as the doc still has a lot of details that must be fleshed out.

**Comment by gdr-at-ms** [comment]
By design, we expect `not_null` to be applicable to non-raw pointer types.

**Pull request closed without merging**
