### PR TITLE
Minor refactoring to use <type_traits>.

### PR DESCRIPTION
**Pull request by kernhanda**
Also refactored the use of value in a static_assert.

### CODE REVIEW

**Comment by trebconnell** [comment]
Could use std::enable_if_**t** and other alias templates

**Comment by kernhanda** [comment]
Yup. The only reason I didn't is because I'm unaware of the project's stance on support for C++11 code. There should be some guidelines for contributors in that regard.

**Comment by trebconnell** [comment]
I see them used in other places, but I do agree clearer guidance on style
would be good.

**Comment by gdr-at-ms** [comment]
With `<type_traits>` you could use the `_t` variants; that will take the `typename ...::type` noise out of the picture.

**Comment by neilmacintosh** [comment]
Looks like this has conflicts that need resolving now.

**Comment by gdr-at-ms** [comment]
Yes, we should have a simple statement about what "features" to use.  Roughly, it is C++14 (with minor tweaks for defective compilers).

On Sep 25, 2015, at 9:36 AM, trebconnell <notifications@github.com<mailto:notifications@github.com>> wrote:

I see them used in other places, but I do agree clearer guidance on style
would be good.
On Fri, Sep 25, 2015 at 7:52 AM Kern Handa <notifications@github.com<mailto:notifications@github.com>> wrote:

> Yup. The only reason I didn't is because I'm unaware of the project's
> stance on support for C++11 code. There should be some guidelines for
> contributors in that regard.
>
> -
> Reply to this email directly or view it on GitHub
> <https://github.com/Microsoft/GSL/pull/58#issuecomment-143243971>.
>

-

**Comment by kernhanda** [comment]
Updated to use the C++14 alias templates. Also added fixes for #71 and #72.

**Comment by neilmacintosh** [comment]
Your PR has conflicts and appears to change line endings unnecessarily. Feel free to correct it and try again.

**Comment by kernhanda** [comment]
Resolved conflicts and removed whitespace changes.

**Comment by neilmacintosh** [comment]
I'm afraid the code has moved around a lot underneath this PR. I might close it out at this point, though I'd be very open to receiving a new one that targeted the current codebase.

**Pull request closed without merging**
