### PR TITLE
Make library importable by CMake using find_package

### LINKED ISSUE #715: CMake project not importable using find_package
Currently no GSLConfig.cmake file is installed so find_package can not be used with GSL.

Exporting the targets and having an install script is a crucial requirement for GSL to be used with CMake based package manager like [hunter](https://hunter.sh). Even without any package manager `find_package` is the most clean way to import dependencies in CMake.

The CMakeLists.txt should be changed to include an export and install rule.

### PR DESCRIPTION
**Pull request by ithron**
Currently no GSLConfig.cmake file was installed so find_package could not be used with GSL.
Fixed CMakeLists.txt to install GSLConfig.cmake so that find_package can be used.
Fixes #715.

### CODE REVIEW

**Comment by OvermindDL1** [comment]
Doesn't this conflict with GSLConfig.cmake from the GSL scientific library project that this project's name conflicts with?  Is there any way to prevent one from overwriting the other on the same system?

**Comment by ithron** [comment]
Yes, there is a conflict with GNU Scientific Library.
Changed the package name to Microsoft.GSL. The exported target GSL now resides in the namespace Microsoft.GSL::
So:

`find_package(Microsoft.GSL)`
`target_link_libraries(MyTarget PUBLIC Microsoft.GSL::GSL)`

I think this might be a good compromise.

**Comment by OvermindDL1** [comment]
The namespace is great, but it looks like the filename itself was still `GSLConfig.cmake` on line 86?

**Comment by ithron** [comment]
Ah, yes, only changed the install line. Fixed that. (Microsoft.GSLConfig.cmake)

**Comment by ithron** [comment]
Should be ready now

**Comment by jimvonmoon** [comment]
Has this PR gone stale? It is a great initiative to make GSL available as an imported target. This seems to be the standard approach now.

**Comment by Warchant** [comment]
Please land this fix

**Comment by pr0g** [comment]
Hey there,

I wound up implementing this myself recently for a library I wanted to use the GSL with.

I've created a fork here:

    https://github.com/pr0g/GSL

and the diff looks like this:

    https://github.com/microsoft/GSL/compare/master...pr0g:cmake-find-package.

It's pretty similar to this change - I'm using my fork in my project right now.

I know there's also this PR https://github.com/microsoft/GSL/pull/784 so I don't want to step on anyone's toes but I would love if support could officially be added. I'd be happy to create a PR with my fork/branch if that would help or try and update this one?

Thanks!


Tom

**Comment by JordanMaples** [comment]
Maintainer's call: Marking as duplicate of PR #784

**Pull request closed without merging**
