### PR TITLE
[Travis] enlarge the support matrix

### PR DESCRIPTION
**Pull request by CaseyCarter**
* Build on OSX with Xcode 8
* Build on Linux with Clang 3.6/7/8 and libc++
* Build on Linux with GCC 5/6

### CODE REVIEW

**Comment by neilmacintosh** [comment]
Hey @CaseyCarter, while we wait for this to pass....do you have enough Travis expertise to be able to get us using a more recent version of CMake with our Travis builds? It's holding back a couple of PRs.

**Comment by CaseyCarter** [comment]
> Hey @CaseyCarter, while we wait for this to pass....do you have enough Travis expertise to be able to get us using a more recent version of CMake with our Travis builds?

Since I like you, I will travel back in time to before I submitted this pull request and have it install a more current cmake as part of the build.

**Comment by CaseyCarter** [comment]
There, done.

**Comment by CaseyCarter** [comment]
> I will travel back in time

Just to be clear, this is my "funny" way of telling you that this change already has the requested behavior.

**Comment by neilmacintosh** [comment]
@CaseyCarter I couldn't stop laughing. No, I could. I deserved it for lazily just reading your description and waiting for the CI checks to do the rest. Thank you very much for this magnificent PR, it makes my world a much better place.

**Comment by MikeGitb** [comment]
@CaseyCarter : Is there a way to rerun the tests for existing PRs with the added compiler versions (without adding a new commit)?

**Comment by rianquinn** [comment]
@MikeGitb Yes and now. You can "re-run a build" in Travis CI but since the configuration file is part of the repo, you would need to rebase (which requires a commit) to get the updated config.

**Comment by MikeGitb** [comment]
@rianquinn: Thanks for the explanation. I don't want to rewrite history at the moment, as I'm not sure how that would effect past PR-comments. So I'll go for a merge for now instead.

**Pull request merged**
